
create table productos (
	codigo INT AUTO_INCREMENT PRIMARY KEY,
	producto VARCHAR(50),
	descripcion VARCHAR(50),
	precio_compra DECIMAL(5,2)
);

insert into productos (producto, descripcion, precio_compra) values ('Wine - Beaujolais Villages', 'Pie Shells 10', 373.95);
insert into productos (producto, descripcion, precio_compra) values ('Olives - Green, Pitted', 'Mushroom - Crimini', 122.99);
insert into productos (producto, descripcion, precio_compra) values ('Crab Meat Claw Pasteurise', 'Beans - Fine', 206.3);
insert into productos (producto, descripcion, precio_compra) values ('Versatainer Nc - 888', 'Sauce - Cranberry', 15.77);
insert into productos (producto, descripcion, precio_compra) values ('Nut - Pecan, Pieces', 'V8 Pet', 428.47);
insert into productos (producto, descripcion, precio_compra) values ('Bread Sour Rolls', 'Coffee Guatemala Dark', 426.57);
insert into productos (producto, descripcion, precio_compra) values ('Salt And Pepper Mix - Black', 'Roe - Lump Fish, Black', 421.88);
insert into productos (producto, descripcion, precio_compra) values ('Pastry - Baked Scones - Mini', 'Beef - Bresaola', 162.01);
insert into productos (producto, descripcion, precio_compra) values ('Vegetable - Base', 'Nestea - Ice Tea, Diet', 251.96);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Sesame Thai Dressing', 'Nantucket Cranberry Juice', 21.66);
insert into productos (producto, descripcion, precio_compra) values ('Carbonated Water - Blackberry', 'Chick Peas - Dried', 126.2);
insert into productos (producto, descripcion, precio_compra) values ('Lemon Pepper', 'Sesame Seed', 472.27);
insert into productos (producto, descripcion, precio_compra) values ('Ice Cream - Vanilla', 'Red Snapper - Fillet, Skin On', 48.71);
insert into productos (producto, descripcion, precio_compra) values ('Plastic Arrow Stir Stick', 'Flavouring - Rum', 149.63);
insert into productos (producto, descripcion, precio_compra) values ('Potatoes - Peeled', 'Ham - Smoked, Bone - In', 203.95);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Rosso Toscano Igt', 'Beans - Yellow', 80.11);
insert into productos (producto, descripcion, precio_compra) values ('Sage - Fresh', 'Chinese Foods - Plain Fried Rice', 188.31);
insert into productos (producto, descripcion, precio_compra) values ('Coconut Milk - Unsweetened', 'Caviar - Salmon', 173.86);
insert into productos (producto, descripcion, precio_compra) values ('Taro Root', 'Cheese - Cottage Cheese', 87.49);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Magnotta - Red, Baco', 'Bread - 10 Grain', 388.23);
insert into productos (producto, descripcion, precio_compra) values ('Lemonade - Island Tea, 591 Ml', 'Crab - Meat', 310.7);
insert into productos (producto, descripcion, precio_compra) values ('Bagel - Sesame Seed Presliced', 'Pastry - French Mini Assorted', 200.65);
insert into productos (producto, descripcion, precio_compra) values ('Bread - White, Sliced', 'Oil - Sunflower', 396.61);
insert into productos (producto, descripcion, precio_compra) values ('Vermouth - White, Cinzano', 'Pasta - Cheese / Spinach Bauletti', 62.99);
insert into productos (producto, descripcion, precio_compra) values ('Piping - Bags Quizna', 'Muffin - Blueberry Individual', 370.46);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Blue', 'Basil - Pesto Sauce', 95.1);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Rioja Campo Viejo', 'Chocolate - Pistoles, Lactee, Milk', 260.24);
insert into productos (producto, descripcion, precio_compra) values ('Pork - Chop, Frenched', 'Beef - Tender Tips', 245.17);
insert into productos (producto, descripcion, precio_compra) values ('Sour Cream', 'Broom And Brush Rack Black', 379.12);
insert into productos (producto, descripcion, precio_compra) values ('Energy - Boo - Koo', 'Arctic Char - Fillets', 185.84);
insert into productos (producto, descripcion, precio_compra) values ('Pate - Peppercorn', 'Sole - Iqf', 482.47);
insert into productos (producto, descripcion, precio_compra) values ('Soup Campbells Turkey Veg.', 'Cheese - Shred Cheddar / Mozza', 125.33);
insert into productos (producto, descripcion, precio_compra) values ('Mini - Vol Au Vents', 'Cookie Dough - Chunky', 276.35);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Detalini, White, Fresh', 'Sausage - Meat', 322.09);
insert into productos (producto, descripcion, precio_compra) values ('Slt - Individual Portions', 'Mousse - Mango', 284.55);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Prosecco Valdobiaddene', 'Garlic Powder', 204.8);
insert into productos (producto, descripcion, precio_compra) values ('Knife Plastic - White', 'Split Peas - Yellow, Dry', 124.48);
insert into productos (producto, descripcion, precio_compra) values ('Pears - Anjou', 'Onions - Red Pearl', 106.36);
insert into productos (producto, descripcion, precio_compra) values ('Mushroom - Porcini Frozen', 'Roe - Lump Fish, Red', 226.8);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Shank, Pieces', 'Chervil - Fresh', 245.12);
insert into productos (producto, descripcion, precio_compra) values ('Oranges', 'Foil - Round Foil', 375.53);
insert into productos (producto, descripcion, precio_compra) values ('Table Cloth 144x90 White', 'Sage Derby', 11.99);
insert into productos (producto, descripcion, precio_compra) values ('Cinnamon - Ground', 'Truffle - Whole Black Peeled', 416.96);
insert into productos (producto, descripcion, precio_compra) values ('Butcher Twine 4r', 'Pail With Metal Handle 16l White', 358.57);
insert into productos (producto, descripcion, precio_compra) values ('Basil - Pesto Sauce', 'Wine - Semi Dry Riesling Vineland', 15.85);
insert into productos (producto, descripcion, precio_compra) values ('Mix - Cappucino Cocktail', 'Sugar - White Packet', 25.12);
insert into productos (producto, descripcion, precio_compra) values ('Soy Protein', 'Sprite - 355 Ml', 457.36);
insert into productos (producto, descripcion, precio_compra) values ('Lobster - Cooked', 'Lotus Rootlets - Canned', 169.41);
insert into productos (producto, descripcion, precio_compra) values ('Absolut Citron', 'Truffle Cups - White Paper', 49.0);
insert into productos (producto, descripcion, precio_compra) values ('Tea - Vanilla Chai', 'Food Colouring - Orange', 253.87);
insert into productos (producto, descripcion, precio_compra) values ('Ecolab Digiclean Mild Fm', 'Pasta - Fusili Tri - Coloured', 21.65);
insert into productos (producto, descripcion, precio_compra) values ('Coke - Diet, 355 Ml', 'Split Peas - Green, Dry', 498.15);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Raisin', 'Cassis', 472.56);
insert into productos (producto, descripcion, precio_compra) values ('Hand Towel', 'Apple - Delicious, Red', 123.42);
insert into productos (producto, descripcion, precio_compra) values ('Carbonated Water - Blackberry', 'Flavouring - Rum', 24.38);
insert into productos (producto, descripcion, precio_compra) values ('Cake - Lemon Chiffon', 'Kale - Red', 167.1);
insert into productos (producto, descripcion, precio_compra) values ('Pepper - Chili Powder', 'Cake Circle, Foil, Scallop', 263.19);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Casillero Del Diablo', 'Spice - Paprika', 108.23);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Lou Black Shiraz', 'Sauce - Thousand Island', 110.63);
insert into productos (producto, descripcion, precio_compra) values ('Shichimi Togarashi Peppeers', 'Wine - Niagara,vqa Reisling', 202.48);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Lolla Rosa', 'Beans - Fine', 15.47);
insert into productos (producto, descripcion, precio_compra) values ('Kiwano', 'Bread - Malt', 85.78);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Prosecco Valdobiaddene', 'Juice - Happy Planet', 224.84);
insert into productos (producto, descripcion, precio_compra) values ('Bandage - Fexible 1x3', 'Soup - French Can Pea', 125.39);
insert into productos (producto, descripcion, precio_compra) values ('Fish - Base, Bouillion', 'Honey - Liquid', 38.32);
insert into productos (producto, descripcion, precio_compra) values ('Sambuca - Opal Nera', 'Carbonated Water - Peach', 44.75);
insert into productos (producto, descripcion, precio_compra) values ('Vector Energy Bar', 'Fish - Scallops, Cold Smoked', 44.44);
insert into productos (producto, descripcion, precio_compra) values ('Scotch - Queen Anne', 'Icecream Bar - Del Monte', 277.17);
insert into productos (producto, descripcion, precio_compra) values ('Syrup - Monin - Granny Smith', 'Juice - Orange, Concentrate', 479.75);
insert into productos (producto, descripcion, precio_compra) values ('Salmon - Whole, 4 - 6 Pounds', 'Chinese Foods - Cantonese', 341.78);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Lamancha Do Crianza', 'Pork - Inside', 499.76);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Gorgonzola', 'Mushroom - Shitake, Dry', 408.16);
insert into productos (producto, descripcion, precio_compra) values ('Vodka - Moskovskaya', 'Lamb - Leg, Bone In', 184.38);
insert into productos (producto, descripcion, precio_compra) values ('Oil - Hazelnut', 'Cake - French Pear Tart', 456.24);
insert into productos (producto, descripcion, precio_compra) values ('Boogies', 'Bread - Raisin', 35.82);
insert into productos (producto, descripcion, precio_compra) values ('Lobster - Baby, Boiled', 'Tumeric', 139.29);
insert into productos (producto, descripcion, precio_compra) values ('Tart Shells - Savory, 4', 'Coffee Swiss Choc Almond', 83.91);
insert into productos (producto, descripcion, precio_compra) values ('Cup - Paper 10oz 92959', 'Dikon', 331.21);
insert into productos (producto, descripcion, precio_compra) values ('Bagel - 12 Grain Preslice', 'Puree - Mango', 164.71);
insert into productos (producto, descripcion, precio_compra) values ('Mountain Dew', 'Veal - Liver', 22.2);
insert into productos (producto, descripcion, precio_compra) values ('Eggplant - Asian', 'Mushroom - Chanterelle Frozen', 2.64);
insert into productos (producto, descripcion, precio_compra) values ('Ecolab Crystal Fusion', 'Iced Tea Concentrate', 35.52);
insert into productos (producto, descripcion, precio_compra) values ('Miso - Soy Bean Paste', 'Mushroom - White Button', 229.17);
insert into productos (producto, descripcion, precio_compra) values ('Food Colouring - Red', 'Beef - Ground, Extra Lean, Fresh', 252.13);
insert into productos (producto, descripcion, precio_compra) values ('Pepsi - 600ml', 'Stock - Chicken, White', 390.13);
insert into productos (producto, descripcion, precio_compra) values ('Sesame Seed Black', 'Wine - White, Antinore Orvieto', 476.95);
insert into productos (producto, descripcion, precio_compra) values ('Pears - Bartlett', 'Fiddlehead - Frozen', 494.31);
insert into productos (producto, descripcion, precio_compra) values ('Buffalo - Short Rib Fresh', 'Coconut - Creamed, Pure', 112.94);
insert into productos (producto, descripcion, precio_compra) values ('Kale - Red', 'Sauce - White, Mix', 199.76);
insert into productos (producto, descripcion, precio_compra) values ('Juice - Tomato, 48 Oz', 'Towels - Paper / Kraft', 462.01);
insert into productos (producto, descripcion, precio_compra) values ('Cinnamon Buns Sticky', 'Wine - Ej Gallo Sonoma', 286.5);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red, Wolf Blass, Yellow', 'Cup - 3.5oz, Foam', 399.64);
insert into productos (producto, descripcion, precio_compra) values ('Ham - Cooked', 'Wine - Baron De Rothschild', 101.81);
insert into productos (producto, descripcion, precio_compra) values ('Pork - Sausage, Medium', 'Lettuce - Treviso', 222.05);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Malt', 'Cup - 8oz Coffee Perforated', 278.89);
insert into productos (producto, descripcion, precio_compra) values ('Salt - Seasoned', 'Steel Wool S.o.s', 411.12);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Treviso', 'Cream Of Tartar', 461.35);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Calabrese Baguette', 'Anchovy In Oil', 122.12);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red, Black Opal Shiraz', 'Ecolab - Medallion', 296.35);
insert into productos (producto, descripcion, precio_compra) values ('Pepper - Roasted Red', 'Edible Flower - Mixed', 421.66);
insert into productos (producto, descripcion, precio_compra) values ('Coffee Guatemala Dark', 'Vermacelli - Sprinkles, Assorted', 341.53);
insert into productos (producto, descripcion, precio_compra) values ('Cod - Black Whole Fillet', 'Pecan Raisin - Tarts', 164.56);
insert into productos (producto, descripcion, precio_compra) values ('Carbonated Water - Orange', 'Cheese Cheddar Processed', 451.39);
insert into productos (producto, descripcion, precio_compra) values ('Oxtail - Cut', 'Vacuum Bags 12x16', 296.83);
insert into productos (producto, descripcion, precio_compra) values ('Yogurt - Strawberry, 175 Gr', 'Venison - Denver Leg Boneless', 179.02);
insert into productos (producto, descripcion, precio_compra) values ('Sobe - Lizard Fuel', 'Island Oasis - Strawberry', 83.88);
insert into productos (producto, descripcion, precio_compra) values ('Coffee - French Vanilla Frothy', 'Sauce - Hoisin', 489.49);
insert into productos (producto, descripcion, precio_compra) values ('Compound - Strawberry', 'Cranberries - Dry', 454.75);
insert into productos (producto, descripcion, precio_compra) values ('Beets - Pickled', 'Cheese - Cheddarsliced', 35.49);
insert into productos (producto, descripcion, precio_compra) values ('Dasheen', 'Garlic Powder', 380.6);
insert into productos (producto, descripcion, precio_compra) values ('Arizona - Plum Green Tea', 'Blueberries - Frozen', 271.9);
insert into productos (producto, descripcion, precio_compra) values ('Beets - Mini Golden', 'Vaccum Bag 10x13', 457.85);
insert into productos (producto, descripcion, precio_compra) values ('Lemonade - Pineapple Passion', 'Mustard - Dijon', 21.44);
insert into productos (producto, descripcion, precio_compra) values ('Godiva White Chocolate', 'Wine - Domaine Boyar Royal', 7.55);
insert into productos (producto, descripcion, precio_compra) values ('Chocolate Bar - Reese Pieces', 'Spaghetti Squash', 450.05);
insert into productos (producto, descripcion, precio_compra) values ('Bread - English Muffin', 'Veal - Osso Bucco', 279.16);
insert into productos (producto, descripcion, precio_compra) values ('Pears - Fiorelle', 'Garlic - Primerba, Paste', 283.24);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Clam Chowder, Dry Mix', 'Appetizer - Lobster Phyllo Roll', 445.39);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Gewurztraminer Pierre', 'Crab - Dungeness, Whole, live', 402.06);
insert into productos (producto, descripcion, precio_compra) values ('Radish', 'Cheese - Pont Couvert', 327.02);
insert into productos (producto, descripcion, precio_compra) values ('Squeeze Bottle', 'Wine - Red, Black Opal Shiraz', 445.61);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Focaccia Quarter', 'Corn Shoots', 60.08);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Shank, Pieces', 'Foie Gras', 491.4);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Soave Folonari', 'Broom Handle', 107.2);
insert into productos (producto, descripcion, precio_compra) values ('Prunes - Pitted', 'Wine - Jaboulet Cotes Du Rhone', 42.7);
insert into productos (producto, descripcion, precio_compra) values ('Peach - Fresh', 'Beets', 164.52);
insert into productos (producto, descripcion, precio_compra) values ('Canada Dry', 'Quail Eggs - Canned', 97.44);
insert into productos (producto, descripcion, precio_compra) values ('Appetizer - Tarragon Chicken', 'Pumpkin', 123.73);
insert into productos (producto, descripcion, precio_compra) values ('Pastrami', 'Quail - Eggs, Fresh', 154.49);
insert into productos (producto, descripcion, precio_compra) values ('The Pop Shoppe - Black Cherry', 'Squash - Acorn', 445.73);
insert into productos (producto, descripcion, precio_compra) values ('Nut - Macadamia', 'Pasta - Orecchiette', 31.6);
insert into productos (producto, descripcion, precio_compra) values ('Garlic - Primerba, Paste', 'Cheese - Cheddar, Mild', 327.23);
insert into productos (producto, descripcion, precio_compra) values ('Crab - Dungeness, Whole', 'Bag - Clear 7 Lb', 12.54);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Mini Red Organic', 'Syrup - Monin, Irish Cream', 146.86);
insert into productos (producto, descripcion, precio_compra) values ('Rum - Coconut, Malibu', 'Garlic Powder', 497.2);
insert into productos (producto, descripcion, precio_compra) values ('Ginger - Ground', 'Gingerale - Schweppes, 355 Ml', 141.28);
insert into productos (producto, descripcion, precio_compra) values ('Lid Coffee Cup 8oz Blk', 'Lettuce - Escarole', 463.58);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red, Wolf Blass, Yellow', 'Bar Bran Honey Nut', 287.1);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Loin', 'Nutmeg - Ground', 145.56);
insert into productos (producto, descripcion, precio_compra) values ('Ice - Clear, 300 Lb For Carving', 'Taro Root', 257.87);
insert into productos (producto, descripcion, precio_compra) values ('Aspic - Clear', 'Beer - Blue Light', 400.3);
insert into productos (producto, descripcion, precio_compra) values ('Poppy Seed', 'Octopus - Baby, Cleaned', 24.58);
insert into productos (producto, descripcion, precio_compra) values ('Lamb - Loin, Trimmed, Boneless', 'Bread - Rolls, Rye', 355.63);
insert into productos (producto, descripcion, precio_compra) values ('Loquat', 'Mushroom - Trumpet, Dry', 421.43);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Toasted Head', 'Monkfish - Fresh', 337.82);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Beef Conomme, Dry', 'Corn Syrup', 142.1);
insert into productos (producto, descripcion, precio_compra) values ('Hinge W Undercut', 'Pan Grease', 14.57);
insert into productos (producto, descripcion, precio_compra) values ('Bagel - Whole White Sesame', 'Waffle Stix', 164.94);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Wheat Baguette', 'Olives - Green, Pitted', 125.75);
insert into productos (producto, descripcion, precio_compra) values ('Beans - Green', 'Mince Meat - Filling', 172.36);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Cream Of Potato / Leek', 'Neckerchief Blck', 332.59);
insert into productos (producto, descripcion, precio_compra) values ('Spinach - Frozen', 'Pastry - Baked Cinnamon Stick', 305.12);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Heinekin', 'Veal - Insides Provini', 397.01);
insert into productos (producto, descripcion, precio_compra) values ('Ice Cream Bar - Hageen Daz To', 'Pork - Sausage, Medium', 177.18);
insert into productos (producto, descripcion, precio_compra) values ('Longos - Chicken Cordon Bleu', 'Cake - Sheet Strawberry', 398.65);
insert into productos (producto, descripcion, precio_compra) values ('Peas Snow', 'Pepperoni Slices', 294.84);
insert into productos (producto, descripcion, precio_compra) values ('Lemonade - Mandarin, 591 Ml', 'Soup - Beef, Base Mix', 42.71);
insert into productos (producto, descripcion, precio_compra) values ('Pail For Lid 1537', 'Oil - Olive, Extra Virgin', 133.17);
insert into productos (producto, descripcion, precio_compra) values ('Island Oasis - Pina Colada', 'Plate Foam Laminated 9in Blk', 280.1);
insert into productos (producto, descripcion, precio_compra) values ('Jam - Blackberry, 20 Ml Jar', 'Lid Tray - 12in Dome', 96.59);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Bocconcini', 'Ice Cream - Strawberry', 406.65);
insert into productos (producto, descripcion, precio_compra) values ('Blueberries - Frozen', 'Emulsifier', 463.72);
insert into productos (producto, descripcion, precio_compra) values ('Jolt Cola', 'Hand Towel', 113.63);
insert into productos (producto, descripcion, precio_compra) values ('Oil - Margarine', 'Sole - Fillet', 348.9);
insert into productos (producto, descripcion, precio_compra) values ('Tomatoes Tear Drop', 'Soy Protein', 316.04);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Puligny Montrachet A.', 'Turkey Leg With Drum And Thigh', 277.47);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Knorr, Chicken Noodle', 'Berry Brulee', 165.47);
insert into productos (producto, descripcion, precio_compra) values ('Cleaner - Pine Sol', 'Nestea - Iced Tea', 464.01);
insert into productos (producto, descripcion, precio_compra) values ('Sword Pick Asst', 'Lamb - Rack', 22.13);
insert into productos (producto, descripcion, precio_compra) values ('Cookies - Oreo, 4 Pack', 'Lemonade - Black Cherry, 591 Ml', 302.76);
insert into productos (producto, descripcion, precio_compra) values ('Pate Pans Yellow', 'Truffle Cups Green', 64.44);
insert into productos (producto, descripcion, precio_compra) values ('Iced Tea - Lemon, 340ml', 'Tea - Jasmin Green', 246.51);
insert into productos (producto, descripcion, precio_compra) values ('Bread Crumbs - Panko', 'Danishes - Mini Cheese', 19.69);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Rhine Riesling Wolf Blass', 'Puff Pastry - Sheets', 400.89);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Spring Mix', 'Venison - Denver Leg Boneless', 435.57);
insert into productos (producto, descripcion, precio_compra) values ('Raspberries - Fresh', 'Wonton Wrappers', 13.58);
insert into productos (producto, descripcion, precio_compra) values ('Wine - White, Antinore Orvieto', 'Haggis', 313.87);
insert into productos (producto, descripcion, precio_compra) values ('Muffin - Mix - Bran And Maple 15l', 'Campari', 430.46);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Campbells Beef Stew', 'Oil - Truffle, Black', 430.62);
insert into productos (producto, descripcion, precio_compra) values ('Sour Cream', 'Wine - Chianti Classica Docg', 493.47);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red, Cooking', 'Spoon - Soup, Plastic', 26.96);
insert into productos (producto, descripcion, precio_compra) values ('Garam Masala Powder', 'Juice Peach Nectar', 481.64);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Cabernet Sauvignon', 'Energy Drink - Franks Pineapple', 91.61);
insert into productos (producto, descripcion, precio_compra) values ('Rice - Brown', 'Melon - Cantaloupe', 5.23);
insert into productos (producto, descripcion, precio_compra) values ('Cookies - Englishbay Chochip', 'Cheese Cloth', 484.7);
insert into productos (producto, descripcion, precio_compra) values ('Olives - Green, Pitted', 'Beer - True North Lager', 416.32);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Soya, Dark', 'Cut Wakame - Hanawakaba', 487.87);
insert into productos (producto, descripcion, precio_compra) values ('Onions Granulated', 'Cheese - Romano, Grated', 264.48);
insert into productos (producto, descripcion, precio_compra) values ('Pastry - Apple Large', 'Bagelers - Cinn / Brown', 243.74);
insert into productos (producto, descripcion, precio_compra) values ('Grapefruit - Pink', 'Soup - Knorr, Classic Can. Chili', 158.7);
insert into productos (producto, descripcion, precio_compra) values ('Dried Apple', 'Paper - Brown Paper Mini Cups', 303.15);
insert into productos (producto, descripcion, precio_compra) values ('Bacardi Mojito', 'Butter Sweet', 88.48);
insert into productos (producto, descripcion, precio_compra) values ('Olives - Kalamata', 'Compound - Passion Fruit', 233.36);
insert into productos (producto, descripcion, precio_compra) values ('Tray - 12in Rnd Blk', 'Waffle Stix', 359.24);
insert into productos (producto, descripcion, precio_compra) values ('Chickensplit Half', 'Chutney Sauce', 141.65);
insert into productos (producto, descripcion, precio_compra) values ('Cumin - Ground', 'Bread - Raisin Walnut Pull', 362.03);
insert into productos (producto, descripcion, precio_compra) values ('Eggplant - Regular', 'Soup - Campbells Bean Medley', 225.38);
insert into productos (producto, descripcion, precio_compra) values ('Wine - White, French Cross', 'Parasol Pick Stir Stick', 72.09);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Penne, Lisce, Dry', 'Bread - White, Sliced', 42.13);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Cambozola', 'Chinese Lemon Pork', 28.46);
insert into productos (producto, descripcion, precio_compra) values ('Coriander - Seed', 'Curry Powder', 418.9);
insert into productos (producto, descripcion, precio_compra) values ('Corn - Cream, Canned', 'Monkfish - Fresh', 150.29);
insert into productos (producto, descripcion, precio_compra) values ('Oyster - In Shell', 'Blackberries', 352.74);
insert into productos (producto, descripcion, precio_compra) values ('Rosemary - Dry', 'Basil - Dry, Rubbed', 203.36);
insert into productos (producto, descripcion, precio_compra) values ('Island Oasis - Pina Colada', 'Cake - Box Window 10x10x2.5', 26.07);
insert into productos (producto, descripcion, precio_compra) values ('Shrimp - Baby, Warm Water', 'Ocean Spray - Kiwi Strawberry', 224.73);
insert into productos (producto, descripcion, precio_compra) values ('Salad Dressing', 'Bok Choy - Baby', 153.35);
insert into productos (producto, descripcion, precio_compra) values ('Icecream - Dstk Super Cone', 'Extract Vanilla Pure', 343.77);
insert into productos (producto, descripcion, precio_compra) values ('Salt And Pepper Mix - White', 'Soup - Campbells Beef Strogonoff', 10.32);
insert into productos (producto, descripcion, precio_compra) values ('Vol Au Vents', 'Soup - Knorr, Country Bean', 297.57);
insert into productos (producto, descripcion, precio_compra) values ('Tequila - Sauza Silver', 'Pie Pecan', 366.43);
insert into productos (producto, descripcion, precio_compra) values ('Butcher Twine 4r', 'Foam Cup 6 Oz', 157.81);
insert into productos (producto, descripcion, precio_compra) values ('Sole - Iqf', 'Hot Choc Vending', 88.74);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Chianti Classica Docg', 'Peas - Frozen', 317.49);
insert into productos (producto, descripcion, precio_compra) values ('Nut - Pecan, Pieces', 'Water - Mineral, Natural', 109.23);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Mini, Stem On', 'Quail - Whole, Boneless', 93.58);
insert into productos (producto, descripcion, precio_compra) values ('Salmon Steak - Cohoe 6 Oz', 'Parasol Pick Stir Stick', 141.45);
insert into productos (producto, descripcion, precio_compra) values ('Cup - Translucent 7 Oz Clear', 'Tart Shells - Sweet, 2', 310.51);
insert into productos (producto, descripcion, precio_compra) values ('Mince Meat - Filling', 'Grand Marnier', 488.82);
insert into productos (producto, descripcion, precio_compra) values ('Sultanas', 'Mints - Striped Red', 146.06);
insert into productos (producto, descripcion, precio_compra) values ('Vinegar - Tarragon', 'Corn Kernels - Frozen', 286.2);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Cheddar With Claret', 'Vinegar - Rice', 311.78);
insert into productos (producto, descripcion, precio_compra) values ('Mix - Cappucino Cocktail', 'Tofu - Soft', 240.39);
insert into productos (producto, descripcion, precio_compra) values ('Quail - Jumbo', 'Maintenance Removal Charge', 99.24);
insert into productos (producto, descripcion, precio_compra) values ('Beef - Ground Medium', 'Water - Mineral, Carbonated', 9.66);
insert into productos (producto, descripcion, precio_compra) values ('Pie Filling - Pumpkin', 'Compound - Rum', 309.7);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Ermite Bleu', 'Carbonated Water - Cherry', 297.65);
insert into productos (producto, descripcion, precio_compra) values ('Grapes - Green', 'Chutney Sauce - Mango', 469.48);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Dark Rye, Loaf', 'Halibut - Steaks', 161.64);
insert into productos (producto, descripcion, precio_compra) values ('Melon - Honey Dew', 'Tilapia - Fillets', 261.08);
insert into productos (producto, descripcion, precio_compra) values ('V8 Splash Strawberry Banana', 'Temperature Recording Station', 269.22);
insert into productos (producto, descripcion, precio_compra) values ('Rum - Spiced, Captain Morgan', 'Filter - Coffee', 333.64);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Steamwhistle', 'Black Currants', 315.12);
insert into productos (producto, descripcion, precio_compra) values ('Nut - Pumpkin Seeds', 'Chocolate - Milk', 462.55);
insert into productos (producto, descripcion, precio_compra) values ('Trout - Rainbow, Fresh', 'Soup - Campbells Beef Strogonoff', 183.58);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Fontina', 'Daves Island Stinger', 298.56);
insert into productos (producto, descripcion, precio_compra) values ('Oil - Pumpkinseed', 'Cheese - Cheddarsliced', 415.53);
insert into productos (producto, descripcion, precio_compra) values ('Beef - Roasted, Cooked', 'Carrots - Mini, Stem On', 22.42);
insert into productos (producto, descripcion, precio_compra) values ('Ostrich - Prime Cut', 'Wine - Masi Valpolocell', 186.17);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Brisket, Provimi,bnls', 'Mousse - Passion Fruit', 184.37);
insert into productos (producto, descripcion, precio_compra) values ('Syrup - Monin - Passion Fruit', 'Potatoes - Pei 10 Oz', 388.4);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Sleeman Fine Porter', 'Cabbage - Red', 63.79);
insert into productos (producto, descripcion, precio_compra) values ('Fiddlehead - Frozen', 'Sobe - Orange Carrot', 239.39);
insert into productos (producto, descripcion, precio_compra) values ('Chilli Paste, Ginger Garlic', 'Piping Jelly - All Colours', 279.93);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Salsa', 'Crab - Meat Combo', 338.83);
insert into productos (producto, descripcion, precio_compra) values ('French Kiss Vanilla', 'Durian Fruit', 263.07);
insert into productos (producto, descripcion, precio_compra) values ('Onions - Red', 'Lid - 3oz Med Rec', 358.67);
insert into productos (producto, descripcion, precio_compra) values ('Tart - Butter Plain Squares', 'Octopus - Baby, Cleaned', 57.22);
insert into productos (producto, descripcion, precio_compra) values ('Coffee Beans - Chocolate', 'Wine - Balbach Riverside', 105.62);
insert into productos (producto, descripcion, precio_compra) values ('Pepper - Scotch Bonnet', 'Oil - Truffle, Black', 322.2);
insert into productos (producto, descripcion, precio_compra) values ('Red Currant Jelly', 'Vegetable - Base', 408.53);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Pita, Mini', 'Wine - Placido Pinot Grigo', 82.24);
insert into productos (producto, descripcion, precio_compra) values ('V8 - Berry Blend', 'Octopus - Baby, Cleaned', 357.06);
insert into productos (producto, descripcion, precio_compra) values ('Goulash Seasoning', 'Pepper - Chipotle, Canned', 224.39);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Fettuccine, Egg, Fresh', 'Squeeze Bottle', 221.35);
insert into productos (producto, descripcion, precio_compra) values ('Salmon - Canned', 'Sauce Bbq Smokey', 157.93);
insert into productos (producto, descripcion, precio_compra) values ('Potatoes - Instant, Mashed', 'Sword Pick Asst', 240.81);
insert into productos (producto, descripcion, precio_compra) values ('Duck - Legs', 'Piping Jelly - All Colours', 377.85);
insert into productos (producto, descripcion, precio_compra) values ('Carroway Seed', 'Chocolate - Mi - Amere Semi', 280.21);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Brie, Triple Creme', 'Lentils - Green, Dry', 183.64);
insert into productos (producto, descripcion, precio_compra) values ('Shrimp - Black Tiger 16/20', 'Longan', 24.37);
insert into productos (producto, descripcion, precio_compra) values ('Munchies Honey Sweet Trail Mix', 'Muffin - Mix - Creme Brule 15l', 40.07);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Paulaner Hefeweisse', 'Potatoes - Fingerling 4 Oz', 82.07);
insert into productos (producto, descripcion, precio_compra) values ('Doilies - 5, Paper', 'Soup - Campbells, Chix Gumbo', 460.32);
insert into productos (producto, descripcion, precio_compra) values ('Asparagus - Mexican', 'Cheese - Pont Couvert', 323.85);
insert into productos (producto, descripcion, precio_compra) values ('Flour - So Mix Cake White', 'Yukon Jack', 415.45);
insert into productos (producto, descripcion, precio_compra) values ('Sprouts - Peppercress', 'Tomato - Tricolor Cherry', 454.02);
insert into productos (producto, descripcion, precio_compra) values ('Beans - Navy, Dry', 'Sobe - Cranberry Grapefruit', 377.96);
insert into productos (producto, descripcion, precio_compra) values ('Chilli Paste, Sambal Oelek', 'Turkey - Whole, Fresh', 168.11);
insert into productos (producto, descripcion, precio_compra) values ('Sausage - Andouille', 'Beer - Paulaner Hefeweisse', 153.68);
insert into productos (producto, descripcion, precio_compra) values ('Mints - Striped Red', 'Pastry - Key Limepoppy Seed Tea', 449.68);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Segura Viudas Aria Brut', 'Stock - Beef, Brown', 191.57);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Riesling Dr. Pauly', 'Potatoes - Mini White 3 Oz', 269.87);
insert into productos (producto, descripcion, precio_compra) values ('Relish', 'Beef - Bones, Cut - Up', 457.67);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Ranch Dressing', 'Lid Tray - 16in Dome', 166.73);
insert into productos (producto, descripcion, precio_compra) values ('Kahlua', 'Pork - Bones', 466.65);
insert into productos (producto, descripcion, precio_compra) values ('Chevere Logs', 'Otomegusa Dashi Konbu', 8.44);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Canadian Pea, Dry Mix', 'Rum - Mount Gay Eclipes', 346.52);
insert into productos (producto, descripcion, precio_compra) values ('Southern Comfort', 'Red Currants', 264.34);
insert into productos (producto, descripcion, precio_compra) values ('Whmis - Spray Bottle Trigger', 'Appetizer - Lobster Phyllo Roll', 303.45);
insert into productos (producto, descripcion, precio_compra) values ('Lotus Leaves', 'Roe - Flying Fish', 97.43);
insert into productos (producto, descripcion, precio_compra) values ('Pie Shell - 9', 'Ecolab - Orange Frc, Cleaner', 263.57);
insert into productos (producto, descripcion, precio_compra) values ('Basil - Pesto Sauce', 'Pepper - Black, Crushed', 128.44);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Penne, Lisce, Dry', 'Filter - Coffee', 108.24);
insert into productos (producto, descripcion, precio_compra) values ('Plate - Foam, Bread And Butter', 'Goulash Seasoning', 172.18);
insert into productos (producto, descripcion, precio_compra) values ('Coffee Cup 12oz 5342cd', 'Sauce - Rosee', 467.04);
insert into productos (producto, descripcion, precio_compra) values ('Tumeric', 'Cake Circle, Foil, Scallop', 298.52);
insert into productos (producto, descripcion, precio_compra) values ('Bandage - Fexible 1x3', 'Dr. Pepper - 355ml', 305.62);
insert into productos (producto, descripcion, precio_compra) values ('Trueblue - Blueberry', 'Wine - Red, Marechal Foch', 243.33);
insert into productos (producto, descripcion, precio_compra) values ('Fib N9 - Prague Powder', 'Tea - Honey Green Tea', 498.65);
insert into productos (producto, descripcion, precio_compra) values ('Waffle Stix', 'Cheese - Goat With Herbs', 180.43);
insert into productos (producto, descripcion, precio_compra) values ('Snapple - Mango Maddness', 'Aspic - Amber', 445.58);
insert into productos (producto, descripcion, precio_compra) values ('Longos - Greek Salad', 'Tart Shells - Sweet, 3', 185.86);
insert into productos (producto, descripcion, precio_compra) values ('Sprite, Diet - 355ml', 'Foam Tray S2', 318.96);
insert into productos (producto, descripcion, precio_compra) values ('Flour - Buckwheat, Dark', 'Durian Fruit', 179.82);
insert into productos (producto, descripcion, precio_compra) values ('Goulash Seasoning', 'Goulash Seasoning', 331.49);
insert into productos (producto, descripcion, precio_compra) values ('Brownies - Two Bite, Chocolate', 'Crab - Imitation Flakes', 190.45);
insert into productos (producto, descripcion, precio_compra) values ('Cookie Dough - Oatmeal Rasin', 'Beans - Long, Chinese', 47.46);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Sour Sticks With Onion', 'Wine - Hardys Bankside Shiraz', 283.01);
insert into productos (producto, descripcion, precio_compra) values ('Tart Shells - Barquettes, Savory', 'Munchies Honey Sweet Trail Mix', 17.03);
insert into productos (producto, descripcion, precio_compra) values ('Star Anise, Whole', 'Carbonated Water - Lemon Lime', 410.03);
insert into productos (producto, descripcion, precio_compra) values ('Asparagus - White, Canned', 'Marsala - Sperone, Fine, D.o.c.', 201.18);
insert into productos (producto, descripcion, precio_compra) values ('Tomatoes - Heirloom', 'Bread - White, Sliced', 34.38);
insert into productos (producto, descripcion, precio_compra) values ('Crush - Orange, 355ml', 'Blueberries', 230.48);
insert into productos (producto, descripcion, precio_compra) values ('Wine - White, Colubia Cresh', 'Chicken - Soup Base', 430.05);
insert into productos (producto, descripcion, precio_compra) values ('Cinnamon Rolls', 'Crackers - Graham', 123.72);
insert into productos (producto, descripcion, precio_compra) values ('Lobak', 'Pasta - Tortellini, Fresh', 408.7);
insert into productos (producto, descripcion, precio_compra) values ('Beef - Montreal Smoked Brisket', 'Pastry - Chocolate Chip Muffin', 86.67);
insert into productos (producto, descripcion, precio_compra) values ('Grapefruit - Pink', 'Oil - Shortening,liqud, Fry', 271.12);
insert into productos (producto, descripcion, precio_compra) values ('Tomatoes - Grape', 'Shrimp - 16/20, Iqf, Shell On', 99.94);
insert into productos (producto, descripcion, precio_compra) values ('Pepper - Paprika, Hungarian', 'Pastry - Chocolate Marble Tea', 232.37);
insert into productos (producto, descripcion, precio_compra) values ('Coffee - Decaffeinato Coffee', 'Ecolab - Balanced Fusion', 77.45);
insert into productos (producto, descripcion, precio_compra) values ('Flower - Dish Garden', 'Tray - 12in Rnd Blk', 180.85);
insert into productos (producto, descripcion, precio_compra) values ('Gatorade - Xfactor Berry', 'Pasta - Shells, Medium, Dry', 430.59);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Chenin Blanc K.w.v.', 'Wine - Magnotta - Cab Sauv', 28.49);
insert into productos (producto, descripcion, precio_compra) values ('Steampan - Lid For Half Size', 'Irish Cream - Butterscotch', 473.88);
insert into productos (producto, descripcion, precio_compra) values ('Beer - Maudite', 'Table Cloth - 53x69 Colour', 362.68);
insert into productos (producto, descripcion, precio_compra) values ('Egg Patty Fried', 'Foam Tray S2', 206.99);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Jumbo', 'Absolut Citron', 169.38);
insert into productos (producto, descripcion, precio_compra) values ('Lentils - Red, Dry', 'Bread - Onion Focaccia', 190.37);
insert into productos (producto, descripcion, precio_compra) values ('Sausage - Breakfast', 'Wine - Casillero Deldiablo', 165.87);
insert into productos (producto, descripcion, precio_compra) values ('Beef - Tongue, Fresh', 'Flour - Bread', 300.39);
insert into productos (producto, descripcion, precio_compra) values ('Calypso - Pineapple Passion', 'Mushrooms - Honey', 281.38);
insert into productos (producto, descripcion, precio_compra) values ('Turkey - Breast, Double', 'Coffee - 10oz Cup 92961', 87.09);
insert into productos (producto, descripcion, precio_compra) values ('Beef - Tenderlion, Center Cut', 'Cardamon Ground', 175.32);
insert into productos (producto, descripcion, precio_compra) values ('Oven Mitts - 15 Inch', 'Chips - Miss Vickies', 182.64);
insert into productos (producto, descripcion, precio_compra) values ('Worcestershire Sauce', 'Nantucket Cranberry Juice', 442.84);
insert into productos (producto, descripcion, precio_compra) values ('Flavouring - Rum', 'Spinach - Baby', 73.9);
insert into productos (producto, descripcion, precio_compra) values ('Skirt - 24 Foot', 'Onions Granulated', 488.72);
insert into productos (producto, descripcion, precio_compra) values ('Mushroom - Chantrelle, Fresh', 'Coke - Classic, 355 Ml', 196.24);
insert into productos (producto, descripcion, precio_compra) values ('Appetizer - Southwestern', 'Raspberries - Frozen', 372.24);
insert into productos (producto, descripcion, precio_compra) values ('Uniform Linen Charge', 'Veal - Inside, Choice', 13.44);
insert into productos (producto, descripcion, precio_compra) values ('Corn - On The Cob', 'Mince Meat - Filling', 128.55);
insert into productos (producto, descripcion, precio_compra) values ('Muffin Batt - Choc Chk', 'Chicken Thigh - Bone Out', 6.24);
insert into productos (producto, descripcion, precio_compra) values ('Chicken - Whole', 'Tuna - Loin', 30.07);
insert into productos (producto, descripcion, precio_compra) values ('Hipnotiq Liquor', 'Strawberries - California', 124.5);
insert into productos (producto, descripcion, precio_compra) values ('Nantucket Pine Orangebanana', 'Fish - Base, Bouillion', 324.94);
insert into productos (producto, descripcion, precio_compra) values ('Flour Pastry Super Fine', 'Container - Clear 32 Oz', 464.7);
insert into productos (producto, descripcion, precio_compra) values ('Flavouring - Raspberry', 'Jagermeister', 418.94);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Swiss', 'Tomato Puree', 456.22);
insert into productos (producto, descripcion, precio_compra) values ('Sobe - Berry Energy', 'Garam Marsala', 496.36);
insert into productos (producto, descripcion, precio_compra) values ('Clams - Littleneck, Whole', 'Garbage Bag - Clear', 335.95);
insert into productos (producto, descripcion, precio_compra) values ('Grand Marnier', 'Pasta - Lasagna Noodle, Frozen', 466.9);
insert into productos (producto, descripcion, precio_compra) values ('Chervil - Fresh', 'Pineapple - Golden', 303.01);
insert into productos (producto, descripcion, precio_compra) values ('Pork - Butt, Boneless', 'Bacardi Limon', 358.22);
insert into productos (producto, descripcion, precio_compra) values ('Appetizer - Lobster Phyllo Roll', 'Curry Paste - Madras', 238.17);
insert into productos (producto, descripcion, precio_compra) values ('Beans - Black Bean, Dry', 'Glass Clear 7 Oz Xl', 120.36);
insert into productos (producto, descripcion, precio_compra) values ('Vodka - Moskovskaya', 'Daves Island Stinger', 198.57);
insert into productos (producto, descripcion, precio_compra) values ('Duck - Breast', 'Dill Weed - Dry', 437.44);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Campbells, Creamy', 'Campari', 297.22);
insert into productos (producto, descripcion, precio_compra) values ('Cocoa Feuilletine', 'Bread - White Epi Baguette', 298.12);
insert into productos (producto, descripcion, precio_compra) values ('Sambuca - Ramazzotti', 'Canada Dry', 325.84);
insert into productos (producto, descripcion, precio_compra) values ('Liqueur - Melon', 'Sauce - Salsa', 429.87);
insert into productos (producto, descripcion, precio_compra) values ('Lid - High Heat, Super Clear', 'Jam - Blackberry, 20 Ml Jar', 302.2);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Linguini, Dry', 'Cake Slab', 286.79);
insert into productos (producto, descripcion, precio_compra) values ('Bar Energy Chocchip', 'Peach - Halves', 260.13);
insert into productos (producto, descripcion, precio_compra) values ('Muffin Mix - Carrot', 'Paper Cocktail Umberlla 80 - 180', 357.44);
insert into productos (producto, descripcion, precio_compra) values ('Urban Zen Drinks', 'Cookie Double Choco', 171.35);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Purple, Organic', 'Mushroom - Portebello', 59.76);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Vodka Blush', 'Salmon - Atlantic, No Skin', 60.75);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Two Oceans Sauvignon', 'Oranges', 88.88);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Mini Red Organic', 'Tart Shells - Sweet, 4', 485.35);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Crozes Hermitage E.', 'Juice - Cranberry 284ml', 105.17);
insert into productos (producto, descripcion, precio_compra) values ('Paper Towel Touchless', 'Carrots - Purple, Organic', 52.25);
insert into productos (producto, descripcion, precio_compra) values ('Mushroom - Shitake, Dry', 'Potatoes - Fingerling 4 Oz', 197.14);
insert into productos (producto, descripcion, precio_compra) values ('Mix - Cocktail Ice Cream', 'Kellogs All Bran Bars', 454.87);
insert into productos (producto, descripcion, precio_compra) values ('Ecolab - Hobart Upr Prewash Arm', 'Bar - Sweet And Salty Chocolate', 62.89);
insert into productos (producto, descripcion, precio_compra) values ('Pork - Ground', 'Foam Espresso Cup Plain White', 253.92);
insert into productos (producto, descripcion, precio_compra) values ('Dry Ice', 'Wine - Red, Metus Rose', 394.3);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Periguita Fonseca', 'Nantucket - 518ml', 416.77);
insert into productos (producto, descripcion, precio_compra) values ('Kale - Red', 'Salmon - Smoked, Sliced', 322.57);
insert into productos (producto, descripcion, precio_compra) values ('Lid - Translucent, 3.5 And 6 Oz', 'Tea - Lemon Scented', 69.71);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Nuckle', 'Oil - Olive, Extra Virgin', 150.82);
insert into productos (producto, descripcion, precio_compra) values ('Pork - Butt, Boneless', 'Sardines', 37.03);
insert into productos (producto, descripcion, precio_compra) values ('Alize Red Passion', 'Table Cloth 81x81 Colour', 378.55);
insert into productos (producto, descripcion, precio_compra) values ('Buffalo - Striploin', 'Sauce - Soya, Dark', 452.15);
insert into productos (producto, descripcion, precio_compra) values ('Crush - Cream Soda', 'Muffin Chocolate Individual Wrap', 209.14);
insert into productos (producto, descripcion, precio_compra) values ('Smirnoff Green Apple Twist', 'Wine - Remy Pannier Rose', 396.67);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Le Cru Du Clocher', 'Chives - Fresh', 99.03);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Escarole', 'Sorrel - Fresh', 36.24);
insert into productos (producto, descripcion, precio_compra) values ('Lamb Rack - Ontario', 'Bread Bowl Plain', 94.0);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Guy Sage Touraine', 'Cabbage - Savoy', 90.29);
insert into productos (producto, descripcion, precio_compra) values ('Longos - Chicken Cordon Bleu', 'Almonds Ground Blanched', 6.91);
insert into productos (producto, descripcion, precio_compra) values ('Monkfish Fresh - Skin Off', 'Cheese - Ermite Bleu', 472.2);
insert into productos (producto, descripcion, precio_compra) values ('Potatoes - Idaho 80 Count', 'Cape Capensis - Fillet', 453.74);
insert into productos (producto, descripcion, precio_compra) values ('Puree - Guava', 'Turkey - Whole, Fresh', 250.67);
insert into productos (producto, descripcion, precio_compra) values ('Cabbage - Red', 'Energy Drink - Franks Pineapple', 186.54);
insert into productos (producto, descripcion, precio_compra) values ('Brocolinni - Gaylan, Chinese', 'Mountain Dew', 172.52);
insert into productos (producto, descripcion, precio_compra) values ('Spaghetti Squash', 'Cheese - Havarti, Salsa', 243.78);
insert into productos (producto, descripcion, precio_compra) values ('Sugar Thermometer', 'Mushroom - Oyster, Fresh', 274.01);
insert into productos (producto, descripcion, precio_compra) values ('Cake - Bande Of Fruit', 'Fish - Base, Bouillion', 476.25);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Colby', 'Rhubarb', 481.67);
insert into productos (producto, descripcion, precio_compra) values ('Loquat', 'Lamb - Loin, Trimmed, Boneless', 89.9);
insert into productos (producto, descripcion, precio_compra) values ('Lobster - Live', 'Snails - Large Canned', 152.31);
insert into productos (producto, descripcion, precio_compra) values ('Pepsi - Diet, 355 Ml', 'Soup Knorr Chili With Beans', 343.01);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Magnotta - Pinot Gris Sr', 'Wine - Prem Select Charddonany', 434.39);
insert into productos (producto, descripcion, precio_compra) values ('Water - Perrier', 'Roe - White Fish', 322.39);
insert into productos (producto, descripcion, precio_compra) values ('Liqueur Banana, Ramazzotti', 'Soup - Boston Clam Chowder', 215.32);
insert into productos (producto, descripcion, precio_compra) values ('Energy Drink Bawls', 'Sherry - Dry', 17.4);
insert into productos (producto, descripcion, precio_compra) values ('Curry Paste - Green Masala', 'Pork - Liver', 38.83);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Roquefort Pappillon', 'Sterno - Chafing Dish Fuel', 353.44);
insert into productos (producto, descripcion, precio_compra) values ('Cactus Pads', 'Cake - Mini Potato Pancake', 291.79);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Green Leaf', 'Sea Urchin', 390.13);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Roll, Calabrese', 'Pork - Inside', 26.69);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Cottage Cheese', 'Coffee Beans - Chocolate', 59.3);
insert into productos (producto, descripcion, precio_compra) values ('Cranberry Foccacia', 'Bread - Dark Rye', 369.12);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Fino Tio Pepe Gonzalez', 'Beer - Sleemans Honey Brown', 370.27);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Port Late Bottled Vintage', 'Ranchero - Primerba, Paste', 338.2);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Prosecco Valdobienne', 'Wine - Red, Gamay Noir', 99.84);
insert into productos (producto, descripcion, precio_compra) values ('Wine La Vielle Ferme Cote Du', 'Straw - Regular', 104.69);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red, Colio Cabernet', 'Alize Sunset', 369.25);
insert into productos (producto, descripcion, precio_compra) values ('Muffins - Assorted', 'Sprite, Diet - 355ml', 223.58);
insert into productos (producto, descripcion, precio_compra) values ('Paper Towel Touchless', 'Wine - Prosecco Valdobienne', 367.26);
insert into productos (producto, descripcion, precio_compra) values ('Mushroom Morel Fresh', 'Nutmeg - Ground', 211.32);
insert into productos (producto, descripcion, precio_compra) values ('Gelatine Leaves - Envelopes', 'Beef - Baby, Liver', 36.25);
insert into productos (producto, descripcion, precio_compra) values ('Sansho Powder', 'Truffle Cups Green', 327.17);
insert into productos (producto, descripcion, precio_compra) values ('Lobster - Tail 6 Oz', 'Table Cloth 53x53 White', 94.4);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Oyster', 'Wine - Sherry Dry Sack, William', 354.43);
insert into productos (producto, descripcion, precio_compra) values ('Juice - Lemon', 'Wine - White, Chardonnay', 165.99);
insert into productos (producto, descripcion, precio_compra) values ('Transfer Sheets', 'Soup - Cream Of Potato / Leek', 203.45);
insert into productos (producto, descripcion, precio_compra) values ('Orange - Canned, Mandarin', 'Oxtail - Cut', 173.46);
insert into productos (producto, descripcion, precio_compra) values ('Trout - Smoked', 'Fish - Artic Char, Cold Smoked', 56.86);
insert into productos (producto, descripcion, precio_compra) values ('Spoon - Soup, Plastic', 'Pepper - Cubanelle', 83.46);
insert into productos (producto, descripcion, precio_compra) values ('Quail - Whole, Bone - In', 'Orange Roughy 4/6 Oz', 339.09);
insert into productos (producto, descripcion, precio_compra) values ('Cream Of Tartar', 'Chickhen - Chicken Phyllo', 93.98);
insert into productos (producto, descripcion, precio_compra) values ('Kaffir Lime Leaves', 'Nantucket Cranberry Juice', 411.43);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Campbells, Minestrone', 'Lamb - Ground', 331.72);
insert into productos (producto, descripcion, precio_compra) values ('Asparagus - Frozen', 'Wine - Red, Antinori Santa', 111.65);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Cappellini, Dry', 'Pepper - White, Whole', 245.81);
insert into productos (producto, descripcion, precio_compra) values ('Shrimp - 150 - 250', 'Seedlings - Mix, Organic', 219.75);
insert into productos (producto, descripcion, precio_compra) values ('Truffle Cups Green', 'Tea - Camomele', 143.49);
insert into productos (producto, descripcion, precio_compra) values ('Pie Filling - Cherry', 'Wine - Hardys Bankside Shiraz', 370.84);
insert into productos (producto, descripcion, precio_compra) values ('Bay Leaf', 'Pastry - Trippleberry Muffin - Mini', 313.42);
insert into productos (producto, descripcion, precio_compra) values ('Table Cloth 72x144 White', 'Amarula Cream', 114.6);
insert into productos (producto, descripcion, precio_compra) values ('Beans - Fine', 'Mustard - Dijon', 221.93);
insert into productos (producto, descripcion, precio_compra) values ('Cabbage - Green', 'Beef - Short Loin', 345.72);
insert into productos (producto, descripcion, precio_compra) values ('Cheese Cloth No 100', 'Oil - Food, Lacquer Spray', 169.25);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Roll, Canadian Dinner', 'Chips - Miss Vickies', 94.78);
insert into productos (producto, descripcion, precio_compra) values ('Plums - Red', 'Kiwi', 398.6);
insert into productos (producto, descripcion, precio_compra) values ('Bagel - Plain', 'Garlic - Peeled', 489.69);
insert into productos (producto, descripcion, precio_compra) values ('Scallops - 20/30', 'Soup - Campbells, Classic Chix', 494.65);
insert into productos (producto, descripcion, precio_compra) values ('Pepper - Jalapeno', 'Vinegar - Red Wine', 213.98);
insert into productos (producto, descripcion, precio_compra) values ('Napkin White - Starched', 'Calypso - Pineapple Passion', 262.76);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Perron Cheddar', 'Fudge - Chocolate Fudge', 478.53);
insert into productos (producto, descripcion, precio_compra) values ('Soup V8 Roasted Red Pepper', 'Sauce - Soy Low Sodium - 3.87l', 451.21);
insert into productos (producto, descripcion, precio_compra) values ('Tomatoes - Cherry, Yellow', 'Beer - Blue Light', 65.84);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Red Oakridge Merlot', 'Cakes Assorted', 415.19);
insert into productos (producto, descripcion, precio_compra) values ('Oranges - Navel, 72', 'Nut - Walnut, Pieces', 352.75);
insert into productos (producto, descripcion, precio_compra) values ('Temperature Recording Station', 'Sauce - Rosee', 496.45);
insert into productos (producto, descripcion, precio_compra) values ('Lemons', 'Cod - Black Whole Fillet', 430.03);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Goat With Herbs', 'Soup - Knorr, Veg / Beef', 382.99);
insert into productos (producto, descripcion, precio_compra) values ('Soup - Knorr, Ministrone', 'Soap - Hand Soap', 495.11);
insert into productos (producto, descripcion, precio_compra) values ('Veal - Shank, Pieces', 'Pork - Ground', 207.34);
insert into productos (producto, descripcion, precio_compra) values ('Clams - Bay', 'Banana - Green', 477.29);
insert into productos (producto, descripcion, precio_compra) values ('Bread - Sticks, Thin, Plain', 'Dasheen', 423.0);
insert into productos (producto, descripcion, precio_compra) values ('Apples - Sliced / Wedge', 'Trout - Smoked', 414.91);
insert into productos (producto, descripcion, precio_compra) values ('Pastry - Baked Cinnamon Stick', 'Pork - Loin, Boneless', 142.79);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Ruffino Chianti', 'Pasta - Canelloni, Single Serve', 330.7);
insert into productos (producto, descripcion, precio_compra) values ('Potatoes - Instant, Mashed', 'Seedlings - Buckwheat, Organic', 237.36);
insert into productos (producto, descripcion, precio_compra) values ('Towel Multifold', 'Squash - Acorn', 295.58);
insert into productos (producto, descripcion, precio_compra) values ('Leeks - Baby, White', 'Olives - Morracan Dired', 490.13);
insert into productos (producto, descripcion, precio_compra) values ('Melon - Watermelon, Seedless', 'Pasta - Lasagna, Dry', 264.14);
insert into productos (producto, descripcion, precio_compra) values ('Cactus Pads', 'Squid - U - 10 Thailand', 287.49);
insert into productos (producto, descripcion, precio_compra) values ('Island Oasis - Cappucino Mix', 'Tarragon - Fresh', 315.67);
insert into productos (producto, descripcion, precio_compra) values ('Anchovy In Oil', 'Beef - Tenderlion, Center Cut', 458.48);
insert into productos (producto, descripcion, precio_compra) values ('Table Cloth 54x54 Colour', 'Cheese - Romano, Grated', 119.61);
insert into productos (producto, descripcion, precio_compra) values ('Bols Melon Liqueur', 'Clams - Bay', 281.05);
insert into productos (producto, descripcion, precio_compra) values ('Crab - Meat', 'Island Oasis - Peach Daiquiri', 446.69);
insert into productos (producto, descripcion, precio_compra) values ('Garbage Bag - Clear', 'Sauce Tomato Pouch', 414.4);
insert into productos (producto, descripcion, precio_compra) values ('Lettuce - Baby Salad Greens', 'Coffee - Decaffeinato Coffee', 401.18);
insert into productos (producto, descripcion, precio_compra) values ('Pasta - Orecchiette', 'Honey - Lavender', 427.88);
insert into productos (producto, descripcion, precio_compra) values ('Cheese - Wine', 'Mountain Dew', 290.88);
insert into productos (producto, descripcion, precio_compra) values ('Muffin Mix - Corn Harvest', 'Pork - Bacon Cooked Slcd', 281.28);
insert into productos (producto, descripcion, precio_compra) values ('Pumpkin', 'Cheese - Brie, Cups 125g', 242.05);
insert into productos (producto, descripcion, precio_compra) values ('Mince Meat - Filling', 'Beer - Steamwhistle', 326.04);
insert into productos (producto, descripcion, precio_compra) values ('Oneshot Automatic Soap System', 'Jam - Marmalade, Orange', 254.83);
insert into productos (producto, descripcion, precio_compra) values ('Cilantro / Coriander - Fresh', 'Water - San Pellegrino', 181.07);
insert into productos (producto, descripcion, precio_compra) values ('Sugar - Individual Portions', 'Foie Gras', 396.88);
insert into productos (producto, descripcion, precio_compra) values ('Carrots - Purple, Organic', 'Cup - 4oz Translucent', 450.83);
insert into productos (producto, descripcion, precio_compra) values ('Chambord Royal', 'Cheese - Brie, Cups 125g', 194.67);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Casillero Deldiablo', 'Longos - Penne With Pesto', 357.96);
insert into productos (producto, descripcion, precio_compra) values ('Cookies - Amaretto', 'Sour Puss - Tangerine', 477.4);
insert into productos (producto, descripcion, precio_compra) values ('Ice Cream Bar - Hageen Daz To', 'Arizona - Plum Green Tea', 427.71);
insert into productos (producto, descripcion, precio_compra) values ('Vinegar - Cider', 'Doilies - 5, Paper', 377.11);
insert into productos (producto, descripcion, precio_compra) values ('Butter - Salted, Micro', 'Syrup - Monin - Blue Curacao', 258.15);
insert into productos (producto, descripcion, precio_compra) values ('Artichokes - Jerusalem', 'Wine - Sawmill Creek Autumn', 202.26);
insert into productos (producto, descripcion, precio_compra) values ('Chips - Potato Jalapeno', 'Artichokes - Jerusalem', 111.73);
insert into productos (producto, descripcion, precio_compra) values ('Star Anise, Whole', 'Wine - Blue Nun Qualitatswein', 489.96);
insert into productos (producto, descripcion, precio_compra) values ('Wine - Hardys Bankside Shiraz', 'Cherries - Bing, Canned', 284.37);
insert into productos (producto, descripcion, precio_compra) values ('Nantucket - Orange Mango Cktl', 'Glaze - Clear', 205.12);
insert into productos (producto, descripcion, precio_compra) values ('Bar - Granola Trail Mix Fruit Nut', 'Arctic Char - Fillets', 2.23);
insert into productos (producto, descripcion, precio_compra) values ('Sprouts - Baby Pea Tendrils', 'Beef - Prime Rib Aaa', 213.74);
insert into productos (producto, descripcion, precio_compra) values ('Muffin - Banana Nut Individual', 'Soup - Chicken And Wild Rice', 406.64);
insert into productos (producto, descripcion, precio_compra) values ('Turkey Leg With Drum And Thigh', 'Sweet Pea Sprouts', 228.69);
insert into productos (producto, descripcion, precio_compra) values ('Sauce - Demi Glace', 'Beef Tenderloin Aaa', 99.45);
insert into productos (producto, descripcion, precio_compra) values ('Onions Granulated', 'Mushroom - Porcini, Dry', 79.75);
insert into productos (producto, descripcion, precio_compra) values ('Kellogs Cereal In A Cup', 'Doilies - 12, Paper', 487.05);
insert into productos (producto, descripcion, precio_compra) values ('Sansho Powder', 'Curry Powder', 72.21);
insert into productos (producto, descripcion, precio_compra) values ('Juice - Clamato, 341 Ml', 'Pasta - Fett Alfredo, Single Serve', 181.5);
insert into productos (producto, descripcion, precio_compra) values ('General Purpose Trigger', 'Baking Powder', 46.68);
